### ISSUE TITLE
为什么不用Authorization

### ISSUE THREAD

**Issue by daxiaraoming** [yijianguanzhu/icloud-simple-service#1]
https://github.com/yijianguanzhu/icloud-simple-service/blob/4d90ad5e9fbcc17fc14e9b8431775906fe13ae5f/icloud-api-gateway/src/main/java/com/yijianguanzhu/gateway/security/converter/JwtExtractTokenAuthenticationConverter.java#L46-L49

这里为什么不用默认的Authorization请求头,而选择自定义的X-Token,我正好也遇到需要修改的情况

**Comment by yijianguanzhu** [comment]
这套写法是沿用之前兼容使用websocket stomp的做法，websocket stomp的js不支持修改get请求时的参数，而原生的解析方法post请求和get请求的token名不一样。另外就是不太喜欢原生的解析方式。

**Comment by yijianguanzhu** [comment]
> https://github.com/yijianguanzhu/icloud-simple-service/blob/4d90ad5e9fbcc17fc14e9b8431775906fe13ae5f/icloud-api-gateway/src/main/java/com/yijianguanzhu/gateway/security/converter/JwtExtractTokenAuthenticationConverter.java#L46-L49
> 
> 这里为什么不用默认的Authorization请求头,而选择自定义的X-Token,我正好也遇到需要修改的情况

这套写法是沿用之前兼容使用websocket stomp的做法，websocket stomp的js不支持修改get请求时的参数，而原生的解析方法post请求和get请求的token名不一样。另外就是不太喜欢原生的解析方式。

**Comment by daxiaraoming** [comment]
[5.4版本开始支持了](https://github.com/spring-projects/spring-security/blob/caf4c471053aa23f7c8dc2c2d484450f02657430/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/DefaultBearerTokenResolver.java#L91-L102)

**Comment by yijianguanzhu** [comment]
> [5.4版本开始支持了](https://github.com/spring-projects/spring-security/blob/caf4c471053aa23f7c8dc2c2d484450f02657430/oauth2/oauth2-resource-server/src/main/java/org/springframework/security/oauth2/server/resource/web/DefaultBearerTokenResolver.java#L91-L102)

好吧，我倒没注意

**Comment by daxiaraoming** [comment]
我是在使用阿里云产品时, Authorization被它占用了,所以换成了X-Token,然后搜到了你也是这个自定义名,想着是不是相同的情况
我现在keytool生成的公钥放阿里云这边验签失败

**Comment by yijianguanzhu** [comment]
> 我是在使用阿里云产品时, Authorization被它占用了,所以换成了X-Token,然后搜到了你也是这个自定义名,想着是不是相同的情况 我现在keytool生成的公钥放阿里云这边验签失败

我使用阿里云时没遇到这个情况，不清楚你使用的什么产品，验签失败你可以看看有没有相关说明文档

**Comment by daxiaraoming** [comment]
产品是API网关,里面有个jwt鉴权插件,需要填写jwk
我用 https://github.com/mitreid-connect/mkjwk.org 生成的jwk可以验签成功,用keytool生成的验签失败

**Comment by daxiaraoming** [comment]
> 

阿里云那边找到问题原因是他们的鉴权插件不支持毫秒级的token有效期
